import type { Job } from "@/types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const DEMO_PROFILE_TEXT = `Alex Morgan
Backend Engineer | Java & Cloud Specialist
alex.morgan@email.com

PROFESSIONAL SUMMARY
Backend engineer with 4+ years building scalable microservices using Java, Spring Boot, PostgreSQL, and AWS. Experienced in REST API design, Docker containerization, and CI/CD pipelines.

EXPERIENCE
Backend Engineer — TechNova Solutions (2022–Present)
- Developed scalable Java and Spring Boot backend services handling 2M+ daily requests
- Designed PostgreSQL schemas and optimized query performance by 40%
- Deployed services on AWS using EC2, RDS, and S3
- Containerized applications with Docker and managed CI/CD with Jenkins

Junior Backend Developer — DataFlow Inc (2021–2022)
- Built REST APIs with Java and Spring Boot
- Integrated third-party payment APIs
- Wrote unit and integration tests with JUnit

SKILLS
Java, Spring Boot, PostgreSQL, AWS, Docker, REST APIs, Git, Jenkins, Maven, Microservices, SQL

EDUCATION
B.Tech Computer Science — State University (2021)

CERTIFICATIONS
AWS Certified Cloud Practitioner
`;

export const MOCK_JOBS: Job[] = [
  {
    id: "job-001",
    title: "Senior Backend Engineer",
    company: "CloudScale Systems",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "We are seeking a Senior Backend Engineer to build high-performance microservices. Required: Java, Spring Boot, PostgreSQL, AWS, Docker. Preferred: Kubernetes, Terraform. 4+ years experience. You will design REST APIs, optimize database performance, and deploy cloud-native services.",
    postedAt: minutesAgo(32),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-001",
    applicationUrl: "https://demo.careerradar.ai/apply/job-001",
    salary: "$130,000 - $160,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker", "Kubernetes", "Microservices", "REST APIs"],
  },
  {
    id: "job-002",
    title: "Java Software Engineer",
    company: "FinEdge Technologies",
    location: "New York, NY",
    remoteType: "HYBRID",
    description: "Join our payments platform team. Required: Java, Spring Boot, SQL, REST APIs. 3-5 years experience. Build secure financial services APIs and integrate with PostgreSQL databases.",
    postedAt: minutesAgo(57),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-002",
    applicationUrl: "https://demo.careerradar.ai/apply/job-002",
    salary: "$120,000 - $145,000",
    experience: "3-5 years",
    employmentType: "FULL_TIME",
    skills: ["Java", "Spring Boot", "SQL", "PostgreSQL", "REST APIs", "Git"],
  },
  {
    id: "job-003",
    title: "Platform Engineer",
    company: "InfraCore",
    location: "Remote, Global",
    remoteType: "REMOTE",
    description: "Platform Engineer needed for internal developer platform. Required: AWS, Docker, Kubernetes, Terraform, CI/CD. 4+ years. Preferred: Java, Python. Build and maintain cloud infrastructure.",
    postedAt: hoursAgo(1.72),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-003",
    applicationUrl: "https://demo.careerradar.ai/apply/job-003",
    salary: "$140,000 - $170,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD", "Java", "Python"],
  },
  {
    id: "job-004",
    title: "Cloud Engineer",
    company: "SkyBridge Cloud",
    location: "Austin, TX",
    remoteType: "HYBRID",
    description: "Cloud Engineer to manage AWS infrastructure. Required: AWS, Docker, Linux, networking. Preferred: Kubernetes, Terraform. 3+ years cloud experience.",
    postedAt: hoursAgo(4),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-004",
    applicationUrl: "https://demo.careerradar.ai/apply/job-004",
    salary: "$115,000 - $140,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["AWS", "Docker", "Linux", "Kubernetes", "Terraform", "Networking"],
  },
  {
    id: "job-005",
    title: "DevOps Engineer",
    company: "PipelineOps",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "DevOps Engineer for CI/CD and infrastructure automation. Required: Docker, Kubernetes, Terraform, Jenkins, AWS. 5+ years. Strong scripting in Python or Bash.",
    postedAt: hoursAgo(9),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-005",
    applicationUrl: "https://demo.careerradar.ai/apply/job-005",
    salary: "$135,000 - $165,000",
    experience: "5+ years",
    employmentType: "FULL_TIME",
    skills: ["Docker", "Kubernetes", "Terraform", "Jenkins", "AWS", "Python", "CI/CD"],
  },
  {
    id: "job-006",
    title: "Full Stack Developer",
    company: "WebCraft Labs",
    location: "San Francisco, CA",
    remoteType: "HYBRID",
    description: "Full Stack Developer building React frontend and Node.js backend. Required: React, TypeScript, Node.js, PostgreSQL. 3+ years.",
    postedAt: hoursAgo(12),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-006",
    applicationUrl: "https://demo.careerradar.ai/apply/job-006",
    salary: "$125,000 - $150,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "REST APIs"],
  },
  {
    id: "job-007",
    title: "Frontend Developer",
    company: "UIForge",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "Frontend Developer specializing in React and TypeScript. Required: React, TypeScript, CSS, responsive design. 2+ years.",
    postedAt: daysAgo(1),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-007",
    applicationUrl: "https://demo.careerradar.ai/apply/job-007",
    salary: "$100,000 - $130,000",
    experience: "2+ years",
    employmentType: "FULL_TIME",
    skills: ["React", "TypeScript", "CSS", "JavaScript", "HTML"],
  },
  {
    id: "job-008",
    title: "Data Engineer",
    company: "DataPulse Analytics",
    location: "Seattle, WA",
    remoteType: "HYBRID",
    description: "Data Engineer to build ETL pipelines. Required: Python, SQL, Spark, AWS. 4+ years data engineering experience.",
    postedAt: daysAgo(1),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-008",
    applicationUrl: "https://demo.careerradar.ai/apply/job-008",
    salary: "$130,000 - $155,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Python", "SQL", "Spark", "AWS", "ETL", "Airflow"],
  },
  {
    id: "job-009",
    title: "Machine Learning Engineer",
    company: "AI Nexus",
    location: "Remote, Global",
    remoteType: "REMOTE",
    description: "ML Engineer to deploy production ML models. Required: Python, TensorFlow, PyTorch, MLOps, 5+ years. Strong math and statistics background.",
    postedAt: daysAgo(2),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-009",
    applicationUrl: "https://demo.careerradar.ai/apply/job-009",
    salary: "$150,000 - $190,000",
    experience: "5+ years",
    employmentType: "FULL_TIME",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "Machine Learning", "Statistics"],
  },
  {
    id: "job-010",
    title: "QA Automation Engineer",
    company: "QualityFirst",
    location: "Chicago, IL",
    remoteType: "ONSITE",
    description: "QA Automation Engineer for web and API testing. Required: Selenium, Java, TestNG, REST API testing. 3+ years.",
    postedAt: hoursAgo(6),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-010",
    applicationUrl: "https://demo.careerradar.ai/apply/job-010",
    salary: "$95,000 - $120,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["Playwright", "Selenium", "Java", "TestNG", "REST APIs", "API Testing", "Cypress", "Automation Testing"],
  },
  {
    id: "job-011",
    title: "Site Reliability Engineer",
    company: "ReliableOps",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "SRE to ensure system reliability. Required: Kubernetes, AWS, monitoring, incident response. 4+ years. Preferred: Java, Python.",
    postedAt: hoursAgo(2),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-011",
    applicationUrl: "https://demo.careerradar.ai/apply/job-011",
    salary: "$140,000 - $175,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Kubernetes", "AWS", "Monitoring", "Incident Response", "Java", "Python"],
  },
  {
    id: "job-012",
    title: "Cybersecurity Analyst",
    company: "SecureNet",
    location: "Washington, DC",
    remoteType: "HYBRID",
    description: "Security Analyst for threat detection and response. Required: SIEM, network security, incident response. 3+ years security experience.",
    postedAt: daysAgo(1),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-012",
    applicationUrl: "https://demo.careerradar.ai/apply/job-012",
    salary: "$110,000 - $135,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["SIEM", "Network Security", "Incident Response", "Firewall", "SOC"],
  },
  {
    id: "job-013",
    title: "Backend Developer (Node.js)",
    company: "StartupHub",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "Backend Developer with Node.js and MongoDB. Required: Node.js, Express, MongoDB, REST APIs. 3+ years.",
    postedAt: hoursAgo(3),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-013",
    applicationUrl: "https://demo.careerradar.ai/apply/job-013",
    salary: "$110,000 - $135,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs", "JavaScript"],
  },
  {
    id: "job-014",
    title: "Software Engineer II",
    company: "MegaCorp Tech",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "Software Engineer building distributed systems. Required: Java, distributed systems, SQL. 4+ years. Preferred: AWS, Kafka.",
    postedAt: minutesAgo(45),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-014",
    applicationUrl: "https://demo.careerradar.ai/apply/job-014",
    salary: "$125,000 - $150,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Java", "Distributed Systems", "SQL", "AWS", "Kafka", "Microservices"],
  },
  {
    id: "job-015",
    title: "Technical Support Engineer",
    company: "HelpDesk Pro",
    location: "Denver, CO",
    remoteType: "HYBRID",
    description: "Support engineers for SaaS platform. Required: troubleshooting, Linux, SQL basics, customer communication. 2+ years.",
    postedAt: daysAgo(2),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-015",
    applicationUrl: "https://demo.careerradar.ai/apply/job-015",
    salary: "$70,000 - $90,000",
    experience: "2+ years",
    employmentType: "FULL_TIME",
    skills: ["Troubleshooting", "Linux", "SQL", "Customer Support", "SaaS"],
  },
  {
    id: "job-016",
    title: "Business Analyst (IT)",
    company: "Enterprise Solutions",
    location: "Boston, MA",
    remoteType: "HYBRID",
    description: "IT Business Analyst for requirements gathering and process mapping. Required: SQL, JIRA, Agile. 3+ years.",
    postedAt: daysAgo(3),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-016",
    applicationUrl: "https://demo.careerradar.ai/apply/job-016",
    salary: "$90,000 - $110,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["SQL", "JIRA", "Agile", "Requirements Gathering", "Process Mapping"],
  },
  {
    id: "job-017",
    title: "Mobile Developer (React Native)",
    company: "AppMakers",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "React Native developer for cross-platform mobile apps. Required: React Native, JavaScript, mobile UI. 3+ years.",
    postedAt: daysAgo(1),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-017",
    applicationUrl: "https://demo.careerradar.ai/apply/job-017",
    salary: "$115,000 - $140,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["React Native", "JavaScript", "Mobile UI", "iOS", "Android"],
  },
  {
    id: "job-018",
    title: "Database Administrator",
    company: "DataSecure Inc",
    location: "Dallas, TX",
    remoteType: "ONSITE",
    description: "DBA for PostgreSQL and MySQL administration. Required: PostgreSQL, MySQL, backup/recovery, performance tuning. 5+ years.",
    postedAt: daysAgo(2),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-018",
    applicationUrl: "https://demo.careerradar.ai/apply/job-018",
    salary: "$105,000 - $130,000",
    experience: "5+ years",
    employmentType: "FULL_TIME",
    skills: ["PostgreSQL", "MySQL", "Database Administration", "Performance Tuning", "Backup Recovery"],
  },
  {
    id: "job-019",
    title: "AI Engineer",
    company: "GenAI Labs",
    location: "Remote, Global",
    remoteType: "REMOTE",
    description: "AI Engineer building LLM applications. Required: Python, LangChain, OpenAI API, vector databases. 3+ years ML/AI.",
    postedAt: hoursAgo(8),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-019",
    applicationUrl: "https://demo.careerradar.ai/apply/job-019",
    salary: "$145,000 - $180,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["Python", "LangChain", "OpenAI", "LLM", "Vector Databases", "Machine Learning"],
  },
  {
    id: "job-020",
    title: "Engineering Manager",
    company: "ScaleUp Tech",
    location: "San Jose, CA",
    remoteType: "HYBRID",
    description: "Engineering Manager leading backend team. Required: 7+ years engineering, 2+ years management, Java, cloud architecture.",
    postedAt: daysAgo(3),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-020",
    applicationUrl: "https://demo.careerradar.ai/apply/job-020",
    salary: "$180,000 - $220,000",
    experience: "7+ years",
    employmentType: "FULL_TIME",
    skills: ["Leadership", "Java", "Cloud Architecture", "Team Management", "Agile"],
  },
  {
    id: "job-021",
    title: "Marketing Manager",
    company: "BrandBoost",
    location: "Los Angeles, CA",
    remoteType: "ONSITE",
    description: "Marketing Manager for digital campaigns. Required: SEO, content marketing, analytics. 4+ years marketing experience.",
    postedAt: hoursAgo(5),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-021",
    applicationUrl: "https://demo.careerradar.ai/apply/job-021",
    salary: "$85,000 - $105,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["SEO", "Content Marketing", "Analytics", "Social Media", "Campaign Management"],
  },
  {
    id: "job-022",
    title: "Backend Engineer - Payments",
    company: "PayStream",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "Backend Engineer for payment processing. Required: Java, Spring Boot, PostgreSQL, AWS, Docker. 4+ years fintech experience preferred.",
    postedAt: minutesAgo(90),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-022",
    applicationUrl: "https://demo.careerradar.ai/apply/job-022",
    salary: "$135,000 - $165,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker", "Fintech", "Microservices"],
  },
  {
    id: "job-023",
    title: "Solutions Architect",
    company: "CloudAdvisors",
    location: "Remote, USA",
    remoteType: "REMOTE",
    description: "Solutions Architect for enterprise clients. Required: AWS, system design, 8+ years. Preferred: Kubernetes, Terraform, Java.",
    postedAt: daysAgo(2),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-023",
    applicationUrl: "https://demo.careerradar.ai/apply/job-023",
    salary: "$160,000 - $200,000",
    experience: "8+ years",
    employmentType: "FULL_TIME",
    skills: ["AWS", "System Design", "Kubernetes", "Terraform", "Java", "Architecture"],
  },
  {
    id: "job-024",
    title: "QA Automation Engineer",
    company: "TechMahindra",
    location: "Bangalore, India",
    remoteType: "HYBRID",
    description: "QA Automation Engineer for enterprise banking products. Required: Playwright, Selenium, Java, API Testing, TestNG. 3+ years automation experience.",
    postedAt: minutesAgo(45),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-024",
    applicationUrl: "https://demo.careerradar.ai/apply/job-024",
    salary: "₹12,00,000 - ₹18,00,000",
    experience: "3+ years",
    employmentType: "FULL_TIME",
    skills: ["Playwright", "Selenium", "Java", "API Testing", "TestNG", "Cypress"],
  },
  {
    id: "job-025",
    title: "Senior SDET",
    company: "Flipkart",
    location: "Bangalore, India",
    remoteType: "HYBRID",
    description: "Senior SDET building test frameworks at scale. Required: Playwright, Java, CI/CD, API Testing. Preferred: Kubernetes, AWS.",
    postedAt: hoursAgo(3),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-025",
    applicationUrl: "https://demo.careerradar.ai/apply/job-025",
    salary: "₹20,00,000 - ₹28,00,000",
    experience: "5+ years",
    employmentType: "FULL_TIME",
    skills: ["Playwright", "Selenium", "Java", "CI/CD", "API Testing", "Docker"],
  },
  {
    id: "job-026",
    title: "Backend Engineer",
    company: "Razorpay",
    location: "Bangalore, India",
    remoteType: "REMOTE",
    description: "Backend Engineer for payments infrastructure. Required: Java, Spring Boot, PostgreSQL, AWS. Remote within India.",
    postedAt: hoursAgo(8),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-026",
    applicationUrl: "https://demo.careerradar.ai/apply/job-026",
    salary: "₹18,00,000 - ₹30,00,000",
    experience: "4+ years",
    employmentType: "FULL_TIME",
    skills: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker", "Microservices"],
  },
  {
    id: "job-027",
    title: "QA Lead",
    company: "Infosys",
    location: "Hyderabad, India",
    remoteType: "ONSITE",
    description: "QA Lead for digital transformation projects. Required: Selenium, API Testing, team leadership, Agile. 6+ years QA experience.",
    postedAt: hoursAgo(12),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-027",
    applicationUrl: "https://demo.careerradar.ai/apply/job-027",
    salary: "₹15,00,000 - ₹22,00,000",
    experience: "6+ years",
    employmentType: "FULL_TIME",
    skills: ["Selenium", "API Testing", "Java", "TestNG", "Agile", "Leadership"],
  },
  {
    id: "job-028",
    title: "Software Test Engineer",
    company: "Wipro",
    location: "Pune, India",
    remoteType: "HYBRID",
    description: "Software Test Engineer for product testing. Required: Manual Testing, Automation, Playwright or Selenium, SQL basics.",
    postedAt: minutesAgo(120),
    source: "MOCK",
    sourceUrl: "https://demo.careerradar.ai/jobs/job-028",
    applicationUrl: "https://demo.careerradar.ai/apply/job-028",
    salary: "₹8,00,000 - ₹14,00,000",
    experience: "2+ years",
    employmentType: "FULL_TIME",
    skills: ["Playwright", "Selenium", "Manual Testing", "SQL", "API Testing"],
  },
];

export const DEMO_PROFILE = {
  id: "demo-profile-001",
  name: "Alex Morgan",
  email: "alex.morgan@email.com",
  currentRole: "Backend Engineer",
  professionalSummary:
    "Backend engineer with 4+ years building scalable microservices using Java, Spring Boot, PostgreSQL, and AWS.",
  experienceYears: 4.2,
  skills: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker", "REST APIs", "Git", "Jenkins", "Maven", "Microservices", "SQL"],
  programmingLanguages: ["Java"],
  frameworks: ["Spring Boot"],
  libraries: [],
  cloudTechnologies: ["AWS", "EC2", "RDS", "S3"],
  databases: ["PostgreSQL", "SQL"],
  devOpsTools: ["Docker", "Jenkins", "CI/CD"],
  testingTools: ["JUnit"],
  dataTechnologies: [],
  aiMlTechnologies: [],
  certifications: ["AWS Certified Cloud Practitioner"],
  education: [{ degree: "B.Tech Computer Science", institution: "State University", year: "2021" }],
  projects: [],
  achievements: ["Optimized query performance by 40%", "Built services handling 2M+ daily requests"],
  domainExperience: ["Fintech", "SaaS"],
  roles: [
    {
      title: "Backend Engineer",
      company: "TechNova Solutions",
      duration: "2022–Present",
      responsibilities: [
        "Developed scalable Java and Spring Boot backend services",
        "Designed PostgreSQL schemas and optimized queries",
        "Deployed services on AWS",
      ],
      technologies: ["Java", "Spring Boot", "PostgreSQL", "AWS", "Docker"],
    },
    {
      title: "Junior Backend Developer",
      company: "DataFlow Inc",
      duration: "2021–2022",
      responsibilities: ["Built REST APIs", "Integrated payment APIs", "Wrote unit tests"],
      technologies: ["Java", "Spring Boot", "JUnit"],
    },
  ],
  industries: ["Technology", "SaaS"],
  rawResumeText: DEMO_PROFILE_TEXT,
  confirmed: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
